### PR TITLE
21248 Collect chunks of the same size for uploading to Cloudinary

### PR DESCRIPTION
**Pull request by AndriyStankevych**
Fix for https://github.com/directus/directus/issues/21248 Previous batching collected chunks of different sizes, which caused the error 'Inconsistent chunk sizes.'

## Scope

What's changed:

- Lorem ipsum dolor sit amet
- Consectetur adipiscing elit
- Sed do eiusmod tempor incididunt

## Potential Risks / Drawbacks

- Lorem ipsum dolor sit amet
- Consectetur adipiscing elit

## Review Notes / Questions

- I would like to lorem ipsum
- Special attention should be paid to dolor sit amet

---

Fixes #\<num\>

### CODE REVIEW

**Comment by rijkvanzanten** [comment]
Hey @AndriyStankevych! This PR is merging into your own fork instead of the Directus repo. Mind rebasing it there? Happy to merge and release this as it stands 🙂

**Comment by AndriyStankevych** [comment]
@rijkvanzanten I would be really grateful if you could assist me with this PR, as I'm not entirely sure how to do it properly

**Comment by rijkvanzanten** [comment]
@AndriyStankevych GitHub has a step by step that should hopefully help: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

Alternatively, I can copy/paste the work over to a new branch on the directus/directus repo, but that'd mean you'd lose the credit, so I'd rather try it the other way first. Thanks 🙂

**Comment by AndriyStankevych** [comment]
@rijkvanzanten 
I've created a new one https://github.com/directus/directus/pull/23554. 
I'm totally fine if somebody from your team recreate the fix in appropriate way to merge it.

**Pull request closed without merging**
